# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

stages:
  - stage: BuildServer
    displayName: 'Build Server'
    jobs: 
    - job: NugetTool
      steps:
        - task: NuGetToolInstaller@1
          inputs:
             versionSpec: '4.6.0'
        - task: NuGetCommand@2
          inputs:
            command: 'restore'
            restoreSolution: '**/*.sln'
            feedsToUse: 'select'
    - job: 'UseDotNet'
      displayName: 'Download .Net 6'
      steps:
        - task: UseDotNet@2
          inputs:
            version: '6.x'
        - task: UseDotNet@2
          displayName: 'Install .NET Core SDK'
          inputs:
            version: 6.x
            performMultiLevelLookup: true
            includePreviewVersions: true # Required for preview versions
    - job: 'Build'
      displayName: 'Build Server'
      steps:
        - task: DotNetCoreCLI@2
          displayName: Build
          inputs:
            command: build
            projects: '**/*.csproj'
            arguments: '--configuration $(buildConfiguration)' # Update this to match your need
    - job: Test
      steps:    
       - task: DotNetCoreCLI@2
         inputs:
          command: test
          projects: '**/*Test/*.csproj'
          arguments: '--configuration $(buildConfiguration)'
    - job: Publish
      displayName: "Publish"
      steps:
      - task: DotNetCoreCLI@2
        inputs:
          command: publish
          publishWebProjects: True
          arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
          zipAfterPublish: True
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(Build.ArtifactStagingDirectory)' 
          artifactName: 'FrontR-Back'



